# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
