# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170922_0902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
