# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170922_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.TextField(null=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(default='')),
                ('sex', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('email', models.TextField(null=True)),
                ('state', models.TextField(default='default')),
                ('last_activity', models.DateTimeField(null=True)),
                ('day', models.IntegerField(default=1)),
                ('trainer_id', models.IntegerField(null=True)),
                ('city', models.TextField(null=True)),
                ('job', models.TextField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('target_weight', models.TextField(null=True)),
                ('methodologies', models.TextField(null=True)),
                ('most_difficult', models.TextField(null=True)),
                ('was_result', models.TextField(null=True)),
                ('why_fat_again', models.TextField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
