# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20170924_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('photo', models.TextField()),
            ],
            options={
                'db_table': 'trainer',
            },
        ),
    ]
