# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trainer_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
