# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20170926_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('user_id', 'message_id')]),
        ),
    ]
