# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20170926_1017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
    ]
