# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20170926_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Photo',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
