# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20170926_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_type',
            new_name='role',
        ),
    ]
