# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20170927_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='login',
        ),
    ]
