# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20170927_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(default='', null=True),
        ),
    ]
