# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20170928_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(null=True),
        ),
    ]
