# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20170928_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.TextField(null=True),
        ),
    ]
