# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_message_sender_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
