# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_message_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
