# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_trainer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='amount_of_walking',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='analyzes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='any_injuries',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fat_children',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fats_in_family',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hormonals',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='motivation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='not_eat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relatives_attitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_fat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='why_fat_now',
            field=models.TextField(null=True),
        ),
    ]
