# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20171012_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
