INSERT INTO routing VALUES 
	('pause','text','idle'),
	('default','agree','confirm_name'),
	('default','disagree','cancel'),
	('lets_confirm_name','agree','confirm_last_name'),
	('lets_confirm_name','text','confirm_last_name'),
	('lets_confirm_last_name','agree','select_sex'),
	('lets_confirm_last_name','text','select_sex'),
	('sex','male','type_age'),
	('sex','female','type_age'),
	('age','text','type_email'),
	('email','text','video_intro'),
	('video_intro','agree', 'are_we_continue'),
	('after_intro','agree', 'present_trainer'),
	('trainer','agree', 'are_you_ready'),
	('ready','agree', 'remind_1'),
	('remind_1','agree', 'city'),
	('city','text', 'job'),
	('job','text', 'height'),
	('height','text', 'weight'),
	('weight','text', 'target_weight'),
	('target_weight','text', 'methodologies'),
	('methodologies','text', 'most_difficult'),
	('most_difficult','text', 'was_result'),
	('was_result','text', 'why_fat_again'),
	('why_fat_again','text', 'waiting_from_you'),
	('waiting_materials','agree', 'measurements'),
	('day_2','text', 'tolerancy'),
	('day_2','photo', 'tolerancy'),
	('tolerancy','agree', 'when_start_fat'),
	('tolerancy','text', 'when_start_fat'),
	('start_fat','text', 'why_fat_now'),
	('why_fat','text', 'hormonals'),
	('hormonals','text', 'last_analyzes'),
	('hormonals','disagree', 'last_analyzes'),
	('last_analyzes','text', 'not_eat'),
	('not_eat','text', 'allergy'),
	('allergy','text', 'day_2_end'),
	('day_3','text', 'miron_story'),
	('day_3','photo', 'miron_story'),
	('miron_story','text', 'fats_in_family'),
	('miron_story','agree', 'fats_in_family'),
	('fats_in_family','text', 'fat_children'),
	('fats_in_family','disagree', 'fat_children'),
	('fat_children','disagree', 'relatives_attitude'),
	('fat_children','text', 'relatives_attitude'),
	('relatives_attitude','text', 'amount_of_walking'),
	('relatives_attitude','support', 'amount_of_walking'),
	('relatives_attitude','dissuade', 'amount_of_walking'),
	('amount_of_walking','text', 'any_injuries'),
	('amount_of_walking','many', 'any_injuries'),
	('amount_of_walking','few', 'any_injuries'),
	('amount_of_walking','middling', 'any_injuries'),
	('any_injuries','text', 'motivation'),
	('any_injuries','disagree', 'motivation'),
	('motivation','text', 'final_reminder'),
	('final','text','idle');
